#!/bin/bash
#set -x

DOCKER_IMAGE_MAINTAINER=${DOCKER_IMAGE_MAINTAINER:-ntbc}
DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-oracle-java}
DOCKER_IMAGE=${DOCKER_IMAGE_MAINTAINER}/${DOCKER_IMAGE_NAME}
DOCKER_REGISTRY=${DOCKER_REGISTRY:-}

sudo docker build --tag="${DOCKER_IMAGE}" .

if [ $? -eq 0 -a -z "${DOCKER_REGISTRY}" ]; then
	docker push ${DOCKER_IMAGE}
else
	docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}
fi
